# ----------------------- Anti Macro ------------------- #
# %player% = Player's display name, %cps% = Config.Click %nl% = NewLine
Click: 20
Seconds: 1
Kick_Message: ' %nl% &cYou''re reached more than &8[&6%cps%&8] &cClick per Seconds&8.'
Broadcast_Message: '%nl% &4&l%player% &6is reached more than &8[&e%cps%&8] %nl% &6Click
  Per Seconds&8!'
Join_Message: '%player% &6has joined&8.'
Quit_Message: '%player% &6has left&8.'
hub:
  World: world
  X: -297.02568081963364
  Y: 108.62
  Z: -1747.889701006164
  Yaw: 1.2001057
  Pitch: -1.4999986

    
name1:
- Flamy
- TheMC
- Hyper
- Angry
- Cook
- Machine
- Tangy
- x
- Mine
- Main
- Steve
- Mario
- Evil
- Flash
- Book
- Ender
- I
- Hack
- The
- Master
- Epic
- Mc
- Conan
- Holl
- Power
- Slam
- Demon
- Bless
- Crazy
- Mr
- Mrs
- Sword
- Knite
- Gamer
- Dolphin
- Alpha
- Cruel
- White
- Daniel
- Ghost
- Happy
- Master
- Cool
- Lucky
- Jammy
- Inter
- Sparkly
- Monster
- Fire
- Real
name2:
- Boy's
- The
- Cow
- Surucu
- baboy
- Inferno
- Bacca
- Pro
- Timosha
- Blast
- Green
- Oyuncu
- Ninja
- Leon
- Sensei
- Flyer
- Falcon
- Cavy
- Spy
- Man
- Mobile
- Wolf
- Bretoder
- Star
- Of
- Warden
- Only
- Green
- Red
- Gamer
- Skate
- Soul
- Girl
- TNT
- Slime
- Trable
- Yaman
- Deniz
- Bites
- Map
- Milk
- Robin
- Traho
- Miner
- Troll
- Unlimited
- Monkey
- Turtle
- Live
- Katz
- Yusuf
- Huahwi
- Psycho
- Taru
- sfsd
- Fannr
- Funny
- Donkey
- littery
- Woodie
- Freez
- Carrot
- Melon
- Pumpkin
- Time
- Samas
- Kitz
name3:
- 0
- _99
- MC
- HD
- RG
- 2000
- 2015
- 151
- 153
- CS
- LT
- KM
- CB
- SG
- HG
- BW
- GO
- GG
- 99
- 1
- 10
- RS
- Gamer
- _00
- Zaa
- GM
- TR
- Euros
- PvP
- _TR
- _PvP
- MP
- _MP
- II
- PVO
- Piro
- Keko
- Reyiz
- Aga
- Fly
- 1
- Devs
- 33
- 3D
- The
- _
- Ez
- Player
- Xx
- WP
skins:
- goodthief
- RussianSpy
- Notsuru
- MokkaCicc
- leonellus
- alexgrist
- Foggles
- Snipex01
- johnlmonkey
- Zedo_Mann
- NeoTyrant
- Gedehamsen
- AndrewPH
- Fredbob
- PartyPanctodes
- CrazyJared
- HyperMaster49
- diamondwolf3459
- jimmystovo
- Cameron3
- Showers101
- Atheon554
- Madbrad200
- AndrewPwner
- daveandnick
- Equaliser
- dagger1396
- callofduty825
- MegaMonny1
- ZzombieWarz
- jarrodhigman69
- Florine3106
- AchillesCZ
- ForstodenMessiah
- Sparcy52
- Shadow_Warrior_
- LegoJamesBond
- Bishopcraft
- Oscarina1234
- DirtyCheese
- MrHeadCrab
- Doomkid14
- Stephykins
- Munectodiko
- Doobles
- Deadshot12345
- Farefevil93
- TheSewable
- NovaSupreme
- MissGabsarella
- PoisonPudge
- Deathlord555
- CreeperKing123
- iFailGamer
- xXBurnerx
- Staven88
- MysticMagicks
- Crashdoom
- Solidbretoder
- PitchBlackPL
- Crashdoom
- ashanti_clan
- Pinkie_Pie
- DarkSteam
- MrFlohw
- CaptainOAP
- CallMeBean
- Pladdask
- Karalina
- Braizhauler
- canderous_ordo
- PinkMoneyBay
- Da_creeper50
- LobsterNipples
- guiltypiano
- BloodDeath
- Poturbowany
- Jahmaican
- BlackAngelMusica
- MidgetApple
- SiderianDragon
- GeneralEco
- HerpEaze
- xToasty
- Funtoosh
- SydMontauge
- BlackMark
- Chicken_Face
- MrBowZz
- MageMelwyn
- Overdonegrub
- LDShadowLady