package me.xeme.api;

import java.util.ArrayList;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public class InventoryAPI {

	
	
	public static void EffectInv(Player p) {
		Inventory effectInventory = Bukkit.createInventory(null, 54, "§a§lCosmetics §8» §6§lEffects");
		ItemStack back = new ItemStack(Material.ARROW);
		ItemMeta backm = back.getItemMeta();
		backm.setDisplayName("§cBack");
		ArrayList<String> backLore = new ArrayList<String>();
		backLore.add("");
		backm.setLore(backLore);
		back.setItemMeta(backm);
		effectInventory.setItem(45, back);
	    ItemStack fns = new ItemStack(Material.FLINT_AND_STEEL);
	    ItemMeta fnsm = fns.getItemMeta();
	    fnsm.setDisplayName("§c§lFlame Rings");
	    ArrayList<String> fnsLore = new ArrayList<String>();
	    fnsLore.add("");
	    fnsm.setLore(fnsLore);
	    fns.setItemMeta(fnsm);
	    effectInventory.setItem(13, fns);
	    ItemStack apple = new ItemStack(Material.APPLE);
	    ItemMeta applem = apple.getItemMeta();
	    applem.setDisplayName("§4§lHeart Effect");
	    ArrayList<String> appleLore = new ArrayList<String>();
	    appleLore.add("");
	    applem.setLore(appleLore);
	    apple.setItemMeta(applem);
	    effectInventory.setItem(20, apple);
	    ItemStack reddust = new ItemStack(Material.REDSTONE);
	    ItemMeta reddustm = reddust.getItemMeta();
	    reddustm.setDisplayName("§cRed Dust");
	    ArrayList<String> reddustLore = new ArrayList<String>();
	    reddustLore.add("");
	    reddustm.setLore(reddustLore);
	    reddust.setItemMeta(reddustm);
	    effectInventory.setItem(22, reddust);
	    ItemStack emerald = new ItemStack(Material.EMERALD);
	    ItemMeta emeraldm = emerald.getItemMeta();
	    emeraldm.setDisplayName("§aEmerald Twirl");
	    ArrayList<String> emeraldLore = new ArrayList<String>();
	    emeraldLore.add("");
	    emeraldm.setLore(emeraldLore);
	    emerald.setItemMeta(emeraldm);
	    effectInventory.setItem(24, emerald);
	    ItemStack smoke = new ItemStack(Material.IRON_INGOT);
	    ItemMeta smokem = smoke.getItemMeta();
	    smokem.setDisplayName("§cSmoke");
	    ArrayList<String> smokeLore = new ArrayList<String>();
	    smokeLore.add("");
	    smokem.setLore(smokeLore);
	    smoke.setItemMeta(smokem);
	    effectInventory.setItem(37, smoke);
	    ItemStack lava = new ItemStack(Material.LAVA_BUCKET);
	    ItemMeta lavam = lava.getItemMeta();
	    lavam.setDisplayName("§c§lLava Effect");
	    ArrayList<String> lavaLore = new ArrayList<String>();
	    lavaLore.add("");
	    lavam.setLore(lavaLore);
	    lava.setItemMeta(lavam);
	    effectInventory.setItem(39, lava);
	    ItemStack explode = new ItemStack(Material.TNT);
	    ItemMeta explodem = explode.getItemMeta();
	    explodem.setDisplayName("§7§lExplode");
	    ArrayList<String> explodeLore = new ArrayList<String>();
	    explodeLore.add("");
	    explodem.setLore(explodeLore);
	    explode.setItemMeta(explodem);
	    effectInventory.setItem(41, explode);
	    ItemStack firework = new ItemStack(Material.FIREWORK);
	    ItemMeta fireworkm = firework.getItemMeta();
	    fireworkm.setDisplayName("§aFireWork");
	    ArrayList<String> fireworkLore = new ArrayList<String>();
	    fireworkLore.add("");
	    fireworkm.setLore(fireworkLore);
	    firework.setItemMeta(fireworkm);
	    effectInventory.setItem(43, firework);
	    ItemStack crit = new ItemStack(Material.BOW);
	    ItemMeta critm = crit.getItemMeta();
	    critm.setDisplayName("§bCritical");
	    ArrayList<String> critLore = new ArrayList<String>();
	    critLore.add("");
	    critm.setLore(critLore);
	    crit.setItemMeta(critm);
	    effectInventory.setItem(49, crit);
	    ItemStack cloud = new ItemStack(Material.SNOW_BLOCK);
	    ItemMeta cloudm = cloud.getItemMeta();
	    cloudm.setDisplayName("§f§lCloud");
	    ArrayList<String> cloudLore = new ArrayList<String>();
	    cloudLore.add("");
	    cloudm.setLore(cloudLore);
	    cloud.setItemMeta(cloudm);
	    effectInventory.setItem(0, cloud);
	    ItemStack music = new ItemStack(Material.GREEN_RECORD);
	    ItemMeta musicm = music.getItemMeta();
	    musicm.setDisplayName("§5Music");
	    ArrayList<String> musicLore = new ArrayList<String>();
	    musicLore.add("");
	    musicm.setLore(musicLore);
	    music.setItemMeta(musicm);
	    effectInventory.setItem(8, music);
	    ItemStack close = new ItemStack(Material.REDSTONE_BLOCK);
	    ItemMeta closem = close.getItemMeta();
	    closem.setDisplayName("§4§lClear Effects");
	    ArrayList<String> closeLore = new ArrayList<String>();
	    closeLore.add("");
	    closem.setLore(closeLore);
	    close.setItemMeta(closem);
	    effectInventory.setItem(53, close);
	    ItemStack cam = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta camm = cam.getItemMeta();
	    camm.setDisplayName("");
	    ArrayList<String> camLore = new ArrayList<String>();
	    camLore.add("");
	    camm.setLore(camLore);
	    cam.setItemMeta(camm);
	    effectInventory.setItem(3, cam);
	    ItemStack cam1 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam1m = cam1.getItemMeta();
	    cam1m.setDisplayName("");
	    ArrayList<String> cam1Lore = new ArrayList<String>();
	    cam1Lore.add("");
	    cam1m.setLore(cam1Lore);
	    cam1.setItemMeta(cam1m);
	    effectInventory.setItem(4, cam1);
	    ItemStack cam2 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam2m = cam2.getItemMeta();
	    cam2m.setDisplayName("");
	    ArrayList<String> cam2Lore = new ArrayList<String>();
	    cam2Lore.add("");
	    cam2m.setLore(cam2Lore);
	    cam2.setItemMeta(cam2m);
	    effectInventory.setItem(5, cam2);
	    ItemStack cam3 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam3m = cam3.getItemMeta();
	    camm.setDisplayName("");
	    ArrayList<String> cam3Lore = new ArrayList<String>();
	    cam3Lore.add("");
	    cam3m.setLore(cam3Lore);
	    cam3.setItemMeta(cam3m);
	    effectInventory.setItem(27, cam3);
	    ItemStack cam4 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam4m = cam4.getItemMeta();
	    cam4m.setDisplayName("");
	    ArrayList<String> cam4Lore = new ArrayList<String>();
	    cam4Lore.add("");
	    cam4m.setLore(cam4Lore);
	    cam4.setItemMeta(cam4m);
	    effectInventory.setItem(28, cam4);
	    ItemStack cam5 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam5m = cam5.getItemMeta();
	    cam5m.setDisplayName("");
	    ArrayList<String> cam5Lore = new ArrayList<String>();
	    cam5Lore.add("");
	    cam5m.setLore(cam5Lore);
	    cam5.setItemMeta(cam5m);
	    effectInventory.setItem(29, cam);
	    ItemStack cam6 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam6m = cam6.getItemMeta();
	    cam6m.setDisplayName("");
	    ArrayList<String> cam6Lore = new ArrayList<String>();
	    cam6Lore.add("");
	    cam6m.setLore(cam6Lore);
	    cam6.setItemMeta(cam6m);
	    effectInventory.setItem(30, cam6);
	    ItemStack cam7 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam7m = cam7.getItemMeta();
	    cam7m.setDisplayName("");
	    ArrayList<String> cam7Lore = new ArrayList<String>();
	    cam7Lore.add("");
	    cam7m.setLore(cam7Lore);
	    cam7.setItemMeta(cam7m);
	    effectInventory.setItem(31, cam7);	    
	    ItemStack cam8 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam8m = cam8.getItemMeta();
	    cam8m.setDisplayName("");
	    ArrayList<String> cam8Lore = new ArrayList<String>();
	    cam8Lore.add("");
	    cam8m.setLore(cam8Lore);
	    cam8.setItemMeta(cam8m);
	    effectInventory.setItem(32, cam8);
	    ItemStack cam9 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam9m = cam9.getItemMeta();
	    cam9m.setDisplayName("");
	    ArrayList<String> cam9Lore = new ArrayList<String>();
	    cam9Lore.add("");
	    cam9m.setLore(cam9Lore);
	    cam9.setItemMeta(cam9m);
	    effectInventory.setItem(33, cam9);
	    ItemStack cam10 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam10m = cam10.getItemMeta();
	    cam10m.setDisplayName("");
	    ArrayList<String> cam10Lore = new ArrayList<String>();
	    cam10Lore.add("");
	    cam10m.setLore(cam10Lore);
	    cam10.setItemMeta(cam10m);
	    effectInventory.setItem(34, cam10);
	    ItemStack cam11 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam11m = cam11.getItemMeta();
	    cam11m.setDisplayName("");
	    ArrayList<String> cam11Lore = new ArrayList<String>();
	    cam11Lore.add("");
	    cam11m.setLore(cam11Lore);
	    cam11.setItemMeta(cam11m);
	    effectInventory.setItem(35, cam11);
	    ItemStack cam12 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam12m = cam12.getItemMeta();
	    cam12m.setDisplayName("");
	    ArrayList<String> cam12Lore = new ArrayList<String>();
	    cam12Lore.add("");
	    cam12m.setLore(cam12Lore);
	    cam12.setItemMeta(cam12m);
	    effectInventory.setItem(46, cam12);
	    ItemStack cam13 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam13m = cam13.getItemMeta();
	    cam13m.setDisplayName("");
	    ArrayList<String> cam13Lore = new ArrayList<String>();
	    cam13Lore.add("");
	    cam13m.setLore(cam13Lore);
	    cam13.setItemMeta(cam13m);
	    effectInventory.setItem(47, cam13);
	    ItemStack cam14 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam14m = cam14.getItemMeta();
	    cam14m.setDisplayName("");
	    ArrayList<String> cam14Lore = new ArrayList<String>();
	    cam14Lore.add("");
	    cam14m.setLore(cam14Lore);
	    cam14.setItemMeta(cam14m);
	    effectInventory.setItem(48, cam14);
	    ItemStack cam15 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam15m = cam15.getItemMeta();
	    camm.setDisplayName("");
	    ArrayList<String> cam15Lore = new ArrayList<String>();
	    cam15Lore.add("");
	    cam15m.setLore(cam15Lore);
	    cam15.setItemMeta(cam15m);
	    effectInventory.setItem(50, cam15);
	    ItemStack cam16 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam16m = cam16.getItemMeta();
	    cam16m.setDisplayName("");
	    ArrayList<String> cam16Lore = new ArrayList<String>();
	    cam16Lore.add("");
	    cam16m.setLore(cam16Lore);
	    cam16.setItemMeta(cam16m);
	    effectInventory.setItem(51, cam16);
	    ItemStack cam17 = new ItemStack(Material.STAINED_GLASS_PANE);
	    ItemMeta cam17m = cam.getItemMeta();
	    cam17m.setDisplayName("");
	    ArrayList<String> cam17Lore = new ArrayList<String>();
	    cam17Lore.add("");
	    cam17m.setLore(cam17Lore);
	    cam17.setItemMeta(cam17m);
	    effectInventory.setItem(52, cam17);
}
	
	
}
